// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdczgfyurmdownthonrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkY3pnZnl1cm1kb3dudGhvbnJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMDExNjMsImV4cCI6MjA2OTg3NzE2M30.Ej5P1DI24yXiwHu_Gy56ktUXPp9FhfSdgTL2wcTp5tQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});