name: Deploy Vite app to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

env:
  FRONTEND_PATH: apps/app
  CUSTOM_DOMAIN: ""  # set to e.g. optisentry.com, or leave empty

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        working-directory: ${{ env.FRONTEND_PATH }}
        run: npm ci

      - name: Build
        working-directory: ${{ env.FRONTEND_PATH }}
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: npm run build

      - name: Create env.js (runtime injection)
        run: |
          cat > "${{ env.FRONTEND_PATH }}/dist/env.js" << 'EOF'
          window.__ENV__ = {
            VITE_SUPABASE_URL: "${{ secrets.VITE_SUPABASE_URL }}",
            VITE_SUPABASE_ANON_KEY: "${{ secrets.VITE_SUPABASE_ANON_KEY }}",
          };
          EOF

      - name: SPA fallback + optional CNAME
        run: |
          cp "$FRONTEND_PATH/dist/index.html" "$FRONTEND_PATH/dist/404.html" || true
          if [ -n "${{ env.CUSTOM_DOMAIN }}" ]; then
            echo "${{ env.CUSTOM_DOMAIN }}" > "$FRONTEND_PATH/dist/CNAME"
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.FRONTEND_PATH }}/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
